<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateExternalMetricsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('external_metrics', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('quality_system_id')->unsigned();
            $table->string('code', 45);
            $table->mediumText('normalization_rule');
            $table->string('normalization_data', 400);
            $table->string('description', 2);
            $table->integer('metric_id')->unsigned();
            $table->integer('level');
            $table->integer('type');
            $table->string('pattern', 400);

            $table->foreign('metric_id')->references('id')->on('metrics')->onDelete('cascade');
            $table->foreign('quality_system_id')->references('id')->on('quality_systems')->onDelete('cascade');
        });
        DB::table('external_metrics')->insert(
            array(

                array(
                    'id'                 => 3,
                    'quality_system_id'  => 1,
                    'code'               => 'ncloc',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 3,
                    'level'              => 1,
                    'type'               => 1,
                    'pattern'            => null,
                ),

                array(
                    'id'                 => 7,
                    'quality_system_id'  => 2,
                    'code'               => 'ncloc',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 3,
                    'level'              => 1,
                    'type'               => 1,
                    'pattern'            => null,
                ),

                array(
                    'id'                 => 9,
                    'quality_system_id'  => 1,
                    'code'               => 'blocker_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 5,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "BLOCKER", "type": "BUG"}',
                ),

                array(
                    'id'                 => 10,
                    'quality_system_id'  => 2,
                    'code'               => 'blocker_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 5,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "BLOCKER", "type": "BUG"}',
                ),

                array(
                    'id'                 => 11,
                    'quality_system_id'  => 1,
                    'code'               => 'critical_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 6,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "CRITICAL", "type": "BUG"}',
                ),

                array(
                    'id'                 => 12,
                    'quality_system_id'  => 2,
                    'code'               => 'critical_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 6,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "CRITICAL", "type": "BUG"}',
                ),

                array(
                    'id'                 => 13,
                    'quality_system_id'  => 1,
                    'code'               => 'major_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 7,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MAJOR", "type": "BUG"}',
                ),

                array(
                    'id'                 => 14,
                    'quality_system_id'  => 2,
                    'code'               => 'major_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 7,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MAJOR", "type": "BUG"}',
                ),

                array(
                    'id'                 => 15,
                    'quality_system_id'  => 1,
                    'code'               => 'minor_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 8,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MINOR", "type": "BUG"}',
                ),

                array(
                    'id'                 => 16,
                    'quality_system_id'  => 2,
                    'code'               => 'minor_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 8,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MINOR", "type": "BUG"}',
                ),

                array(
                    'id'                 => 17,
                    'quality_system_id'  => 1,
                    'code'               => 'info_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 9,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "INFO", "type": "BUG"}',
                ),

                array(
                    'id'                 => 18,
                    'quality_system_id'  => 2,
                    'code'               => 'info_bug',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 9,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "INFO", "type": "BUG"}',
                ),

                array(
                    'id'                 => 19,
                    'quality_system_id'  => 1,
                    'code'               => 'blocker_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 10,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "BLOCKER", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 20,
                    'quality_system_id'  => 2,
                    'code'               => 'blocker_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 10,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "BLOCKER", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 21,
                    'quality_system_id'  => 1,
                    'code'               => 'critical_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 11,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "CRITICAL", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 22,
                    'quality_system_id'  => 2,
                    'code'               => 'critical_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 11,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "CRITICAL", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 23,
                    'quality_system_id'  => 1,
                    'code'               => 'major_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 12,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MAJOR", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 24,
                    'quality_system_id'  => 2,
                    'code'               => 'major_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 12,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MAJOR", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 25,
                    'quality_system_id'  => 1,
                    'code'               => 'minor_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 13,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MINOR", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 26,
                    'quality_system_id'  => 2,
                    'code'               => 'minor_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 13,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MINOR", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 27,
                    'quality_system_id'  => 1,
                    'code'               => 'info_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 14,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "INFO", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 28,
                    'quality_system_id'  => 2,
                    'code'               => 'info_vulnerability',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 14,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "INFO", "type": "VULNERABILITY"}',
                ),

                array(
                    'id'                 => 29,
                    'quality_system_id'  => 1,
                    'code'               => 'blocker_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 15,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "BLOCKER", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 30,
                    'quality_system_id'  => 2,
                    'code'               => 'blocker_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 15,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "BLOCKER", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 31,
                    'quality_system_id'  => 1,
                    'code'               => 'critical_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 16,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "CRITICAL", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 32,
                    'quality_system_id'  => 2,
                    'code'               => 'critical_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 16,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "CRITICAL", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 33,
                    'quality_system_id'  => 1,
                    'code'               => 'major_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 17,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MAJOR", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 34,
                    'quality_system_id'  => 2,
                    'code'               => 'major_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 17,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MAJOR", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 35,
                    'quality_system_id'  => 1,
                    'code'               => 'minor_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 18,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MINOR", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 36,
                    'quality_system_id'  => 2,
                    'code'               => 'minor_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 18,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "MINOR", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 37,
                    'quality_system_id'  => 1,
                    'code'               => 'info_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 19,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "INFO", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 38,
                    'quality_system_id'  => 2,
                    'code'               => 'info_code_smell',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 19,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"severity": "INFO", "type": "CODE_SMELL"}',
                ),

                array(
                    'id'                 => 39,
                    'quality_system_id'  => 1,
                    'code'               => 'brain-overload',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 20,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "brain-overload"}',
                ),

                array(
                    'id'                 => 40,
                    'quality_system_id'  => 2,
                    'code'               => 'brain-overload',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 20,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "brain-overload"}',
                ),

                array(
                    'id'                 => 41,
                    'quality_system_id'  => 1,
                    'code'               => 'bad-practice',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 21,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "bad-practice"}',
                ),

                array(
                    'id'                 => 42,
                    'quality_system_id'  => 2,
                    'code'               => 'bad-practice',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 21,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "bad-practice"}',
                ),

                array(
                    'id'                 => 43,
                    'quality_system_id'  => 1,
                    'code'               => 'cert',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 22,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "cert"}',
                ),

                array(
                    'id'                 => 44,
                    'quality_system_id'  => 2,
                    'code'               => 'cert',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 22,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "cert"}',
                ),

                array(
                    'id'                 => 45,
                    'quality_system_id'  => 1,
                    'code'               => 'clumsy',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 23,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "clumsy"}',
                ),

                array(
                    'id'                 => 46,
                    'quality_system_id'  => 2,
                    'code'               => 'clumsy',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 23,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "clumsy"}',
                ),

                array(
                    'id'                 => 47,
                    'quality_system_id'  => 1,
                    'code'               => 'confusing',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 24,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "confusing"}',
                ),

                array(
                    'id'                 => 48,
                    'quality_system_id'  => 2,
                    'code'               => 'confusing',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 24,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "confusing"}',
                ),

                array(
                    'id'                 => 49,
                    'quality_system_id'  => 1,
                    'code'               => 'convention',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 25,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "convention"}',
                ),

                array(
                    'id'                 => 50,
                    'quality_system_id'  => 2,
                    'code'               => 'convention',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 25,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "convention"}',
                ),

                array(
                    'id'                 => 51,
                    'quality_system_id'  => 1,
                    'code'               => 'cwe',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 26,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "cwe"}',
                ),

                array(
                    'id'                 => 52,
                    'quality_system_id'  => 2,
                    'code'               => 'cwe',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 26,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "cwe"}',
                ),

                array(
                    'id'                 => 53,
                    'quality_system_id'  => 1,
                    'code'               => 'design',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 27,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "design"}',
                ),

                array(
                    'id'                 => 54,
                    'quality_system_id'  => 2,
                    'code'               => 'design',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 27,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "design"}',
                ),

                array(
                    'id'                 => 55,
                    'quality_system_id'  => 1,
                    'code'               => 'lock-in',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 28,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "lock-in"}',
                ),

                array(
                    'id'                 => 56,
                    'quality_system_id'  => 2,
                    'code'               => 'lock-in',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 28,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "lock-in"}',
                ),

                array(
                    'id'                 => 57,
                    'quality_system_id'  => 1,
                    'code'               => 'misra',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 29,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "misra"}',
                ),

                array(
                    'id'                 => 58,
                    'quality_system_id'  => 2,
                    'code'               => 'misra',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 29,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "misra"}',
                ),

                array(
                    'id'                 => 59,
                    'quality_system_id'  => 1,
                    'code'               => 'owasp-',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 30,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "owasp-"}',
                ),

                array(
                    'id'                 => 60,
                    'quality_system_id'  => 2,
                    'code'               => 'owasp-',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 30,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "owasp-"}',
                ),

                array(
                    'id'                 => 61,
                    'quality_system_id'  => 1,
                    'code'               => 'pitfall',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 31,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "pitfall"}',
                ),

                array(
                    'id'                 => 62,
                    'quality_system_id'  => 2,
                    'code'               => 'pitfall',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 31,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "pitfall"}',
                ),

                array(
                    'id'                 => 63,
                    'quality_system_id'  => 1,
                    'code'               => 'sans-top25-',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 32,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "sans-top25-"}',
                ),

                array(
                    'id'                 => 64,
                    'quality_system_id'  => 2,
                    'code'               => 'sans-top25-',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 32,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "sans-top25-"}',
                ),

                array(
                    'id'                 => 65,
                    'quality_system_id'  => 1,
                    'code'               => 'security',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 33,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "security"}',
                ),

                array(
                    'id'                 => 66,
                    'quality_system_id'  => 2,
                    'code'               => 'security',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 33,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "security"}',
                ),

                array(
                    'id'                 => 67,
                    'quality_system_id'  => 1,
                    'code'               => 'suspicious',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 34,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "suspicious"}',
                ),

                array(
                    'id'                 => 68,
                    'quality_system_id'  => 2,
                    'code'               => 'suspicious',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 34,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "suspicious"}',
                ),

                array(
                    'id'                 => 69,
                    'quality_system_id'  => 1,
                    'code'               => 'unpredictable',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 35,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "unpredictable"}',
                ),

                array(
                    'id'                 => 70,
                    'quality_system_id'  => 2,
                    'code'               => 'unpredictable',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 35,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "unpredictable"}',
                ),

                array(
                    'id'                 => 71,
                    'quality_system_id'  => 1,
                    'code'               => 'unused',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 36,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "unused"}',
                ),

                array(
                    'id'                 => 72,
                    'quality_system_id'  => 2,
                    'code'               => 'unused',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 36,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "unused"}',
                ),

                array(
                    'id'                 => 73,
                    'quality_system_id'  => 1,
                    'code'               => 'user-experience',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 37,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "user-experience"}',
                ),

                array(
                    'id'                 => 74,
                    'quality_system_id'  => 2,
                    'code'               => 'user-experience',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 37,
                    'level'              => 1,
                    'type'               => 2,
                    'pattern'            => '{"search": "tags", "value": "user-experience"}',
                ),

                array(
                    'id'                 => 75,
                    'quality_system_id'  => 1,
                    'code'               => 'coverage',
                    'normalization_rule' => '{"/":[{ "var" : ["@this"] },100]}',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 38,
                    'level'              => 1,
                    'type'               => 1,
                    'pattern'            => null,
                ),

                array(
                    'id'                 => 76,
                    'quality_system_id'  => 2,
                    'code'               => 'coverage',
                    'normalization_rule' => '{"/":[{ "var" : ["@this"] },100]}',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 38,
                    'level'              => 1,
                    'type'               => 1,
                    'pattern'            => null,
                ),

                array(
                    'id'                 => 77,
                    'quality_system_id'  => 1,
                    'code'               => 'duplicated_blocks',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 39,
                    'level'              => 1,
                    'type'               => 1,
                    'pattern'            => '',
                ),

                array(
                    'id'                 => 78,
                    'quality_system_id'  => 2,
                    'code'               => 'duplicated_blocks',
                    'normalization_rule' => '{ "var" : ["@this"] }',
                    'normalization_data' => '{ "@this" : "@this.value" }',
                    'description'        => null,
                    'metric_id'          => 39,
                    'level'              => 1,
                    'type'               => 1,
                    'pattern'            => '',
                ),
            )
        );


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('external_metrics');
    }
}
